name: Devfile Docs Build

on:
  push:
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['braden-wilson/landing-page']  # Changed
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: build-and-deploy
